baseURL: https://archeryincolorado.org/
languageCode: en-us
title: Archery in Colorado
theme: hugo-fresh

taxonomies:
  - tag: ""
  - group: ""
  - category: ""

frontmatter:
lastmod: ["lastmod", ":git", "date", "publishDate"]

params:
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Archery in Colorado
    # Hero subtitle (optional)
    subtitle: The nonprofit organization to promote the sport of Archery in Colorado
    # Button text
    buttontext: Donate
    # Where the main hero button links to
    buttonlink: "/donate"
    # Hero image (from /images/___)
    image: photos/archery-range.jpg
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Home
    url: /
  - title: Mission
    url: /mission
  - title: Competitions
    url: /competitions
  - title: Board of Directors
    url: /board
  - title: News
    url: /news
  - title: Contact
    url: mailto:board@archeryincolorado.org
  - title: Donate
    url: /donate
    button: true
#  sidebar:
#    # Logo (from /images/logos/___.svg)
#    logo: fresh-square
#    sections:
#    - title: User
#      icon: user
#      links:
#      - text: Profile
#        url: /
#      - text: Account
#        url: /
#      - text: Settings
#        url: /
#    - title: Messages
#      icon: envelope
#      links:
#      - text: Inbox
#        url: /
#      - text: Compose
#        url: /
#    - title: Images
#      icon: image
##      links:
#     - text: Library
#        url: /
#      - text: Upload
#        url: /
#    - title: Settings
#      icon: cog
#      links:
#      - text: User settings
#        url: /
#      - text: App settings
#        url: /
  footer:
    # Logo (from /images/logos/___)
    logo: fresh-white-alt.svg
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    #- link: https://github.com/lucperkins/github-fresh
    #  # Icons are from Font Awesome
    #  icon: github
    #- link: https://dribbble.com/#
    #  icon: dribbble
    - link: https://facebook.com/#
      icon: facebook
    - link: https://twitter.com/lucperkins
      icon: twitter
    - link: https://youtube.com/#
      icon: youtube
    #- link: https://bitbucket.org/#
    #  icon: bitbucket
    bulmalogo: false